export const DOCUMENT_REGISTRY = {
  GOVERNMENT_ID: {
    category: "IDENTITY",
    label: "Government Issued ID",
    expiryRuleYears: null,
    requiredForAll: true,
    onboardingStage: 1,
    regulatoryNote: "Required for identity verification under AML regulations",
  },
  PROOF_OF_ADDRESS: {
    category: "IDENTITY",
    label: "Proof of Address",
    expiryRuleYears: 1,
    requiredForAll: true,
    onboardingStage: 1,
    regulatoryNote: "Must be dated within 12 months",
  },
  SIN_SSN_FORM: {
    category: "IDENTITY",
    label: "SIN / SSN Form",
    expiryRuleYears: null,
    requiredForAll: true,
    onboardingStage: 1,
    regulatoryNote: "Required for CRA / IRS tax reporting",
  },
  KYC_FORM: {
    category: "COMPLIANCE",
    label: "Know Your Client Form",
    expiryRuleYears: 3,
    urgencyThresholdDays: [30, 14, 7],
    requiredForAll: true,
    onboardingStage: null,
    regulatoryNote: "CIRO/FINRA requirement, renew every 3 years",
  },
  AML_VERIFICATION: {
    category: "COMPLIANCE",
    label: "AML Verification",
    expiryRuleYears: 1,
    urgencyThresholdDays: [30, 14, 7],
    requiredForAll: true,
    onboardingStage: null,
    regulatoryNote: "Anti-money laundering annual renewal required",
  },
  NAAF: {
    category: "COMPLIANCE",
    label: "New Account Application Form",
    expiryRuleYears: null,
    requiredForAll: true,
    onboardingStage: 2,
    regulatoryNote: "Required for all new accounts",
  },
  RISK_QUESTIONNAIRE: {
    category: "SUITABILITY",
    label: "Risk Tolerance Questionnaire",
    expiryRuleYears: 2,
    urgencyThresholdDays: [30, 14],
    requiredForAll: true,
    onboardingStage: 2,
    regulatoryNote: "Suitability requirement",
  },
  INVESTMENT_POLICY_STATEMENT: {
    category: "SUITABILITY",
    label: "Investment Policy Statement",
    expiryRuleYears: 2,
    urgencyThresholdDays: [30],
    requiredForAll: false,
    accountTypes: ["INVESTMENT", "CORPORATE"],
    onboardingStage: null,
    regulatoryNote: "Required for specific account types",
  },
  SUITABILITY_ASSESSMENT: {
    category: "SUITABILITY",
    label: "Suitability Assessment",
    expiryRuleYears: 2,
    urgencyThresholdDays: [30, 14],
    requiredForAll: true,
    onboardingStage: null,
    regulatoryNote: "Must be updated with client changes",
  },
  CLIENT_AGREEMENT: {
    category: "LEGAL",
    label: "Client Agreement",
    expiryRuleYears: null,
    requiredForAll: true,
    onboardingStage: 2,
    regulatoryNote: "Master advisor-client agreement",
  },
  FEE_DISCLOSURE: {
    category: "LEGAL",
    label: "Fee Disclosure Document",
    expiryRuleYears: 1,
    urgencyThresholdDays: [30],
    requiredForAll: true,
    onboardingStage: 3,
    regulatoryNote: "Annual disclosure requirement",
  },
  ACCREDITED_INVESTOR_FORM: {
    category: "LEGAL",
    label: "Accredited Investor Declaration",
    expiryRuleYears: 1,
    urgencyThresholdDays: [30, 14],
    requiredForAll: false,
    accountTypes: ["INVESTMENT", "CORPORATE"],
    onboardingStage: null,
    regulatoryNote: "Required for alternative investment eligibility",
  },
  BENEFICIARY_DESIGNATION: {
    category: "ESTATE",
    label: "Beneficiary Designation Form",
    expiryRuleYears: null,
    requiredForAll: true,
    onboardingStage: 3,
    regulatoryNote: "Review after major life events",
  },
  BANKING_INFORMATION: {
    category: "FUNDING",
    label: "Banking Information",
    expiryRuleYears: null,
    requiredForAll: true,
    onboardingStage: 4,
    regulatoryNote: "Required for account funding",
  },
  DEPOSIT_CONFIRMATION: {
    category: "FUNDING",
    label: "Initial Deposit Confirmation",
    expiryRuleYears: null,
    requiredForAll: true,
    onboardingStage: 4,
    regulatoryNote: "Confirms account activation",
  },
} as const;

export type DocumentType = keyof typeof DOCUMENT_REGISTRY;
