export const DOCUMENT_REGISTRY = {
  GOVERNMENT_ID: {
    category: "IDENTITY",
    label: "Government Issued ID",
    expiryRuleYears: null,
    requiredForAll: true,
    onboardingStage: 1,
    regulatoryNote: "Required for identity verification under AML regulations",
  },
  PROOF_OF_ADDRESS: {
    category: "IDENTITY",
    label: "Proof of Address",
    expiryRuleYears: 1,
    requiredForAll: true,
    onboardingStage: 1,
    regulatoryNote: "Must be dated within 12 months",
  },
  SIN_SSN_FORM: {
    category: "IDENTITY",
    label: "SIN / SSN Form",
    expiryRuleYears: null,
    requiredForAll: true,
    onboardingStage: 1,
    regulatoryNote: "Required for CRA / IRS tax reporting",
  },
  KYC_FORM: {
    category: "COMPLIANCE",
    label: "Know Your Client Form",
    expiryRuleYears: 3,
    urgencyThresholdDays: [30, 14, 7],
    requiredForAll: true,
    onboardingStage: null,
    regulatoryNote: "CIRO/FINRA requirement, renew every 3 years",
  },
  AML_VERIFICATION: {
    category: "COMPLIANCE",
    label: "AML Verification",
    expiryRuleYears: 1,
    urgencyThresholdDays: [30, 14, 7],
    requiredForAll: true,
    onboardingStage: null,
    regulatoryNote: "Anti-money laundering annual renewal required",
  },
  NAAF: {
    category: "COMPLIANCE",
    label: "New Account Application Form",
    expiryRuleYears: null,
    requiredForAll: true,
    onboardingStage: 2,
    regulatoryNote: "Required for all new accounts",
  },
  RISK_QUESTIONNAIRE: {
    category: "SUITABILITY",
    label: "Risk Tolerance Questionnaire",
    expiryRuleYears: 2,
    urgencyThresholdDays: [30, 14],
    requiredForAll: true,
    onboardingStage: 2,
    regulatoryNote: "Suitability requirement",
  },
  INVESTMENT_POLICY_STATEMENT: {
    category: "SUITABILITY",
    label: "Investment Policy Statement",
    expiryRuleYears: 2,
    urgencyThresholdDays: [30],
    requiredForAll: false,
    accountTypes: ["INVESTMENT", "CORPORATE"],
    onboardingStage: null,
    regulatoryNote: "Required for specific account types",
  },
  SUITABILITY_ASSESSMENT: {
    category: "SUITABILITY",
    label: "Suitability Assessment",
    expiryRuleYears: 2,
    urgencyThresholdDays: [30, 14],
    requiredForAll: true,
    onboardingStage: null,
    regulatoryNote: "Must be updated with client changes",
  },
  CLIENT_AGREEMENT: {
    category: "LEGAL",
    label: "Client Agreement",
    expiryRuleYears: null,
    requiredForAll: true,
    onboardingStage: 2,
    regulatoryNote: "Master advisor-client agreement",
  },
  FEE_DISCLOSURE: {
    category: "LEGAL",
    label: "Fee Disclosure Document",
    expiryRuleYears: 1,
    urgencyThresholdDays: [30],
    requiredForAll: true,
    onboardingStage: 3,
    regulatoryNote: "Annual disclosure requirement",
  },
  ACCREDITED_INVESTOR_FORM: {
    category: "LEGAL",
    label: "Accredited Investor Declaration",
    expiryRuleYears: 1,
    urgencyThresholdDays: [30, 14],
    requiredForAll: false,
    accountTypes: ["INVESTMENT", "CORPORATE"],
    onboardingStage: null,
    regulatoryNote: "Required for alternative investment eligibility",
  },
  BENEFICIARY_DESIGNATION: {
    category: "ESTATE",
    label: "Beneficiary Designation Form",
    expiryRuleYears: null,
    requiredForAll: true,
    onboardingStage: 3,
    regulatoryNote: "Review after major life events",
  },
  BANKING_INFORMATION: {
    category: "FUNDING",
    label: "Banking Information",
    expiryRuleYears: null,
    requiredForAll: true,
    onboardingStage: 4,
    regulatoryNote: "Required for account funding",
  },
  DEPOSIT_CONFIRMATION: {
    category: "FUNDING",
    label: "Initial Deposit Confirmation",
    expiryRuleYears: null,
    requiredForAll: true,
    onboardingStage: 4,
    regulatoryNote: "Confirms account activation",
  },
  ARTICLES_OF_INCORPORATION: {
    category: "LEGAL",
    label: "Articles of Incorporation",
    expiryRuleYears: null,
    requiredForAll: false,
    accountTypes: ["CORPORATE"],
    onboardingStage: 2,
    regulatoryNote: "Required for corporate entities to prove legal existence",
  },
  AUTHORIZED_SIGNATORY_LIST: {
    category: "LEGAL",
    label: "Authorized Signatory List",
    expiryRuleYears: 1,
    requiredForAll: false,
    accountTypes: ["CORPORATE"],
    onboardingStage: 2,
    regulatoryNote: "Must be updated annually for corporate accounts",
  },
} as const;

export type DocumentType = keyof typeof DOCUMENT_REGISTRY;

export const REQUIRED_DOCUMENTS_BY_ACCOUNT_TYPE: Record<string, DocumentType[]> =
  {
    INDIVIDUAL: [
      "GOVERNMENT_ID",
      "PROOF_OF_ADDRESS",
      "SIN_SSN_FORM",
      "KYC_FORM",
      "AML_VERIFICATION",
      "NAAF",
      "RISK_QUESTIONNAIRE",
      "SUITABILITY_ASSESSMENT",
      "CLIENT_AGREEMENT",
      "FEE_DISCLOSURE",
      "BENEFICIARY_DESIGNATION",
      "BANKING_INFORMATION",
      "DEPOSIT_CONFIRMATION",
    ],
    CORPORATE: [
      "GOVERNMENT_ID",
      "PROOF_OF_ADDRESS",
      "SIN_SSN_FORM",
      "KYC_FORM",
      "AML_VERIFICATION",
      "NAAF",
      "RISK_QUESTIONNAIRE",
      "SUITABILITY_ASSESSMENT",
      "CLIENT_AGREEMENT",
      "FEE_DISCLOSURE",
      "BENEFICIARY_DESIGNATION",
      "BANKING_INFORMATION",
      "DEPOSIT_CONFIRMATION",
      "ARTICLES_OF_INCORPORATION",
      "AUTHORIZED_SIGNATORY_LIST",
      "INVESTMENT_POLICY_STATEMENT",
    ],
  };

export function getRequiredDocs(accountType: string): DocumentType[] {
  // Map RRSP/TFSA/JOINT to INDIVIDUAL for rule simplicity
  if (["RRSP", "TFSA", "JOINT", "INVESTMENT"].includes(accountType)) {
    return REQUIRED_DOCUMENTS_BY_ACCOUNT_TYPE.INDIVIDUAL;
  }
  if (accountType === "CORPORATE") {
    return REQUIRED_DOCUMENTS_BY_ACCOUNT_TYPE.CORPORATE;
  }
  return REQUIRED_DOCUMENTS_BY_ACCOUNT_TYPE.INDIVIDUAL;
}
