export const AccountType = {
  RRSP: "RRSP",
  TFSA: "TFSA",
  INVESTMENT: "INVESTMENT",
  CORPORATE: "CORPORATE",
  JOINT: "JOINT",
} as const;

export const OnboardingStatus = {
  NOT_STARTED: "NOT_STARTED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  STALLED: "STALLED",
} as const;

export const DocumentStatus = {
  MISSING: "MISSING",
  REQUESTED: "REQUESTED",
  PENDING_REVIEW: "PENDING_REVIEW",
  VALID: "VALID",
  EXPIRING_SOON: "EXPIRING_SOON",
  EXPIRED: "EXPIRED",
} as const;

export const DocumentCategory = {
  IDENTITY: "IDENTITY",
  COMPLIANCE: "COMPLIANCE",
  SUITABILITY: "SUITABILITY",
  LEGAL: "LEGAL",
  ESTATE: "ESTATE",
  FUNDING: "FUNDING",
} as const;

export const AgentType = {
  COMPLIANCE: "COMPLIANCE",
  ONBOARDING: "ONBOARDING",
} as const;

export const ActionType = {
  SCAN_VAULT: "SCAN_VAULT",
  NOTIFY_ADVISOR: "NOTIFY_ADVISOR",
  SEND_CLIENT_REMINDER: "SEND_CLIENT_REMINDER",
  ESCALATE_COMPLIANCE: "ESCALATE_COMPLIANCE",
  ESCALATE_MANAGEMENT: "ESCALATE_MANAGEMENT",
  MARK_RESOLVED: "MARK_RESOLVED",
  REQUEST_DOCUMENT: "REQUEST_DOCUMENT",
  VALIDATE_DOCUMENT: "VALIDATE_DOCUMENT",
  ADVANCE_STAGE: "ADVANCE_STAGE",
  COMPLETE_ONBOARDING: "COMPLETE_ONBOARDING",
  ALERT_ADVISOR_STUCK: "ALERT_ADVISOR_STUCK",
} as const;

export const TriggerType = {
  SCHEDULED: "SCHEDULED",
  EVENT_UPLOAD: "EVENT_UPLOAD",
  MANUAL: "MANUAL",
  SIMULATION: "SIMULATION",
} as const;

export const RiskProfile = {
  CONSERVATIVE: "CONSERVATIVE",
  MODERATE: "MODERATE",
  AGGRESSIVE: "AGGRESSIVE",
} as const;

export const AdvisorRole = {
  ADVISOR: "ADVISOR",
  COMPLIANCE_OFFICER: "COMPLIANCE_OFFICER",
} as const;

export const SimulationStatus = {
  PENDING: "PENDING",
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;
