-- WP-P1.1: pKYC-lite TriggerType values (additive; non-destructive)
ALTER TYPE "TriggerType" ADD VALUE 'EVENT_EXPIRY_PROXIMITY';
ALTER TYPE "TriggerType" ADD VALUE 'EVENT_RISK_TIER_CHANGE';
ALTER TYPE "TriggerType" ADD VALUE 'EVENT_PROFILE_MATERIAL_CHANGE';
ALTER TYPE "TriggerType" ADD VALUE 'EVENT_SANCTIONS_PEP';
